[package]
name = "cli"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
# Internal deps
proto.workspace = true
# External deps
clap.workspace = true
prettytable-rs.workspace = true
tokio.workspace = true
