[package]
name = "cli"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
#Internal dependencies
proto.workspace = true
#External dependencies
clap.workspace = true
prettytable-rs.workspace = true
tokio.workspace = true
